Style/MutableConstant:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

Layout/ArrayAlignment:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Lint/BooleanSymbol:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/ScatteredSetup:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/RepeatedExample:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false
