services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && exec ./bin/rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - short_link_network

  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks:
      - short_link_network

volumes:
  db_data:
networks:
  short_link_network:
    driver: bridge